[package]
name = "indosanca"
version = "0.1.0"
authors = ["rifqi nugraha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wat = "1.0"